# Generated by Django 2.2.5 on 2019-10-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artikel',
            new_name='ArtikelModel',
        ),
    ]
