# Generated by Django 2.2.5 on 2019-10-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='publish',
            new_name='published',
        ),
    ]
