# Generated by Django 2.2.5 on 2019-09-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Jurnal', 'Jurnal'), ('Blog', 'Blog'), ('Berita', 'Berita')], default='Blog', max_length=100),
        ),
    ]
