# Generated by Django 2.2.1 on 2019-08-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='nama@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(max_length=200),
        ),
    ]
